---
title: "Preliminary Bike Data Analysis"
author: "Yao Li, Yuhan Luo, Michael Saugstad"
output:
  html_document:
  fig-caption: yes
highlight: tango
theme: united
toc: yes
word_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(caret)
library(e1071)

crash.data <- read.csv("data/All_data.csv", header = TRUE, sep = ",")
#crash.data[["incidence"]][is.na(crash.data[["incidence"]])] <- 0
#crash.data$accidents <- rowSums(crash.data[11:118])
crash.data<- na.omit(crash.data)
crash.data<- na.omit(crash.data)
crash.data <- transform(crash.data,
                        accidents = Accidents_12_B15)

print(table(crash.data$accidents))

#remove zero-accident intersections
crash.data<-subset(crash.data, accidents!=0)
glmfit<- glm(accidents ~ housing_units + household_income + NEAR_DIST + Width_max + Rating_min + Speed_max + ACC_max + OneWay_max,
           data = crash.data,
           family = gaussian())

print(summary(glmfit))

# Construct Training & Testing dataset
set.seed(5)
intrain <- createDataPartition(y = crash.data$accidents, p= 0.8, list = FALSE)
training <- crash.data[intrain,]
testing <- crash.data[-intrain,]
print(dim(training) + dim(testing))

# I'm not sure if we run it as a regression, how to measure the predication performance, so I coverted accidents into categorical in order to run classification.
training[["accidents"]] = factor(training[["accidents"]])
testing[["accidents"]] = factor(testing[["accidents"]])

trctrl <- trainControl(method = "repeatedcv", number = 5, repeats = 3)
set.seed(5)

# SVM
svmfit <- train(accidents ~., data = training, method = "svmLinear",
                    trControl=trctrl,
                    preProcess = c("center", "scale"),
                    tuneLength = 5,
                    probability = TRUE)
print(summary(svmfit))

test_pred <- predict(svmfit, testing)
testing <- transform(testing,pred_acc = test_pred)
print(confusionMatrix(data = testing$pred_acc, reference = testing$accidents))

# ==================================================
# Create visualizations

ggplot(crash.data, aes(x = total_population)) +
  geom_histogram() +
  theme_bw()
ggplot(crash.data, aes(x = housing_units)) +
  geom_histogram() +
  theme_bw()
ggplot(crash.data, aes(x = household_income)) +
  geom_histogram() +
  theme_bw()
ggplot(crash.data, aes(x = NEAR_DIST)) +
  geom_histogram() +
  theme_bw()


ggplot(crash.data, aes(x = total_population, y = accidents)) +
  stat_summary_bin(fun.y = "mean", geom = "bar", binwidth = 10) +
  theme_bw()
ggplot(crash.data, aes(x = NEAR_DIST, y = accidents)) +
  stat_summary_bin(fun.y = "mean", geom = "bar", binwidth = 25) +
  theme_bw()
ggplot(crash.data, aes(x = housing_units, y = accidents)) +
  stat_summary_bin(fun.y = "mean", geom = "bar") +
  theme_bw()
ggplot(crash.data, aes(x = household_income, y = accidents)) +
  stat_summary_bin(fun.y = "mean", geom = "bar", binwidth = 25) +
  theme_bw()

ggplot(crash.data, aes(x = accidents)) +
  geom_histogram() +
  scale_y_log10() +
  theme_bw()
```
